Add 66 to cmake
ckb-next/ckb-next pull request #749
Opened 2021-09-21 17:16 UTC by ndowens

Add 66 to cmake. There are two set 66-PATHs due to Obarun uses /var/lib/66 while Artix uses /etc/66

2021-09-21 17:23 UTC, ndowens commented
One second before merge, found one thing to change

2021-09-27 02:22 UTC, tatokis requested changes
I've been wondering if the service should be called `ckb-next-daemon` instead of simply `ckb-next`, as that's what it's called on all the other inits we support.

Additionally, the path in the 66 service file shouldn't be hardcoded if it gets installed automatically. Cmake should probably generate the path like it does for the other systems.

2021-09-27 02:22 UTC, tatokis commented on src/daemon/CMakeLists.txt
> +    endif ()
This if block should be indented one level to the right.

2021-09-27 02:22 UTC, tatokis commented on src/daemon/CMakeLists.txt
> +		    COMMAND sudo 66-intree | grep -o cbk-next | awk '{print $1; exit}'
I don't think this would work. It's ckb-next, not cbk-next.

2021-09-27 02:22 UTC, tatokis commented on src/daemon/CMakeLists.txt
> +            foreach (daemon IN ITEMS "ckb-daemon" "ckb-next-daemon")
ckb-daemon no longer exists, so there's no chance someone can run it under 66. I don't see a point in keeping it here.

2021-09-27 12:04 UTC, ndowens commented
I will make changes soon

2022-04-13 20:42 UTC, tatokis requested changes
```
tatokis@tatokis-PC:~/ckb-next/ckb-next-ndowens/build$ cmake ..
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- ckb-next version: 0.4.4-102-g26742d9 (Non-release)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/lib/x86_64-linux-gnu/libc.so
-- Checking for module 'libudev'
--   Found libudev, version 245
-- Found UDEV: /usr/lib/x86_64-linux-gnu/libudev.so  
-- systemd detected
-- Generating and importing ckb-next-daemon.service (systemd)
-- Generating and importing ckb-next service (66)
CMake Error: File /home/tatokis/ckb-next/ckb-next-ndowens/linux/66/ckb-next-daemon does not exist.
CMake Error at src/daemon/CMakeLists.txt:433 (configure_file):
  configure_file Problem configuring file


CMake Error at src/daemon/CMakeLists.txt:462 (endif):
  endif An ENDIF command was found outside of a proper IF ENDIF structure.
  Or its arguments did not match the opening IF command.


CMake Error at src/daemon/CMakeLists.txt:527 (install):
  install FILES given no DESTINATION!


-- Found QuaZip: /usr/lib/x86_64-linux-gnu/libquazip5.so  
-- Found PulseAudioSimple: /usr/lib/x86_64-linux-gnu/libpulse-simple.so  
-- Found PulseAudio: /usr/lib/x86_64-linux-gnu/libpulse.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'xcb'
--   Found xcb, version 1.14
-- Checking for module 'xcb-ewmh'
--   Found xcb-ewmh, version 0.4.1
-- Checking for module 'xcb-screensaver'
--   Found xcb-screensaver, version 1.14
-- Generating binary.qrc
-- Importing ckb-next-key.gpg
-- Generating image.qrc
-- Importing ckb-next-monochrome.png
-- Importing ckb-next.png
-- Importing ckb-next_battery_0.png
-- Importing ckb-next_battery_1.png
-- Importing ckb-next_battery_2.png
-- Importing ckb-next_battery_3.png
-- Importing ckb-next_battery_4.png
-- Importing ckb-next_battery_charging.png
-- Importing icon_blank.png
-- Importing icon_mode.png
-- Importing icon_mode1.png
-- Importing icon_mode1_hardware.png
-- Importing icon_mode2.png
-- Importing icon_mode2_hardware.png
-- Importing icon_mode3.png
-- Importing icon_mode3_hardware.png
-- Importing icon_plus.png
-- Importing icon_profile.png
-- Importing icon_profile_hardware.png
-- Importing overlay_darkcore.png
-- Importing overlay_glaive.png
-- Importing overlay_harpoon.png
-- Importing overlay_ironclaw.png
-- Importing overlay_katar.png
-- Importing overlay_m65.png
-- Importing overlay_m95.png
-- Importing overlay_nightsword.png
-- Importing overlay_polaris.png
-- Importing overlay_sabre.png
-- Importing overlay_scimitar.png
-- Importing lightning.svg
-- Importing lightning_disabled.svg
-- Generating translation.qrc
-- Importing de.qm
-- Importing el.qm
-- Importing en_GB.qm
-- Generating and importing ckb-next.desktop
-- Generating and importing ckb-next.autostart.desktop
-- Importing demo profiles and generating text.qrc
-- Importing demoprofile.conf
-- Importing demoprofile_k55.ini
-- Importing demoprofile_m95.ini
-- Importing demoprofile_nightsword.ini
-- Importing demoprofile_polaris.ini
-- Importing demoprofile_st100.ini
-- *** Have SIZEOF void * = 8, so 64-bit
-- Configuring incomplete, errors occurred!
See also "/home/tatokis/ckb-next/ckb-next-ndowens/build/CMakeFiles/CMakeOutput.log".
See also "/home/tatokis/ckb-next/ckb-next-ndowens/build/CMakeFiles/CMakeError.log".
```

2024-09-16 05:43 UTC, closed without merging