Add support for the K70 RGB TKL
ckb-next/ckb-next pull request #809
Opened 2022-04-05 20:16 UTC by minneyar

This adds support for the K70 RGB TKL Champion Series keyboard.  Product page is here: https://www.corsair.com/us/en/Categories/Products/Gaming-Keyboards/RGB-Mechanical-Gaming-Keyboards/K70-RGB-TKL-CHAMPION-SERIES-Mechanical-Gaming-Keyboard/p/CH-9119014-NA

Its interface is fairly similar to the K100, but its key layout is closer to the K63.

I've tested this with my own keyboard, and everything seems fully functional.

Fixes #745

2022-04-15 20:10 UTC, thekhalifa commented
Compiled and tested your branch on mine as well and seems fully functional.
I thought the lock/mute keys were broken, but with ckb running they behave differently to hardware mode.

Thanks for patching this.

2022-04-16 01:27 UTC, minneyar commented
Thanks for testing it!  That did also confuse me a little at first.  It's possible to customize the behavior of the brightness/lock/mute keys in the ckb-next gui; they're under the "Performance" tab in the keyboard settings.  The default behavior is a little different from hardware mode.

2022-05-04 19:14 UTC, tatokis requested changes
Apologies. I had started the review a few days after you opened the PR but completely forgot about it and didn't submit it. I can't remember what else I wanted to bring up, but for now this will do.

2022-05-04 19:14 UTC, tatokis commented on src/gui/kbperf.cpp
> +                          this->modeParent()->bind()->map().model() == KeyMap::K70_TKL)){
Are you sure this is needed?

2022-05-04 19:14 UTC, tatokis commented on src/gui/keymap.cpp
> +        // Very similar to the K63 but with slightly different media button positions
If the only difference between the K63 and the K70TKL is just the top row, you can take the K63 map and then patch the top row on top if it. Should reduce duplicate code

2022-07-05 14:12 UTC, gtjoseph commented
Any progress on this?  @minneyar Are you going to be able to finish?

2022-08-03 17:34 UTC, avanwyk commented
My knowledge of C/C++ is limited, but I could try to take a run at this.

2023-05-06 04:02 UTC, gardotd426 commented
Is this dead?

2023-05-14 02:44 UTC, Hotshot0592 commented
Hey there, new to linux and this site. Please bare with me if I step on any toes in regards to ignorant questions. But, is there any hope of when this patch might be launched or updated?

2023-05-14 02:55 UTC, minneyar commented
I haven't had time to look at this for quite a while and it works as-is, so I had forgotten about it, but I'll see if I can clean it up a bit to bring it up to date with the target branch and address the requested change.

On the other hand, the branch it's based on hasn't been updated since August last year, so I don't know if there are any plans to merge it into the master branch and release it any time soon.

For what it's worth, this branch still works fine as-is if you build and install it yourself.

2023-05-14 03:33 UTC, Hotshot0592 commented
Still learning coding. So is there a thing for now where I could copy paste
into my terminal? And I only know python.

On Sat, May 13, 2023, 9:55 PM minneyar ***@***.***> wrote:

> I haven't had time to look at this for quite a while and it works as-is,
> so I had forgotten about it, but I'll see if I can clean it up a bit to
> bring it up to date with the target branch and address the requested change.
>
> On the other hand, the branch it's based on hasn't been updated since
> August last year, so I don't know if there are any plans to merge it into
> the master branch and release it any time soon.
>
> For what it's worth, this branch still works fine as-is if you build and
> install it yourself.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ckb-next/ckb-next/pull/809#issuecomment-1546794361>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A725RQEXCJXON2EXKHUE7CTXGBCSNANCNFSM5ST33NHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-05-14 03:36 UTC, Hotshot0592 commented
Or would it be better/easier for someone at my level to just go buy a new
compatible keyboard? I was thinking about doing so within the next few
months anyways.

On Sat, May 13, 2023, 9:55 PM minneyar ***@***.***> wrote:

> I haven't had time to look at this for quite a while and it works as-is,
> so I had forgotten about it, but I'll see if I can clean it up a bit to
> bring it up to date with the target branch and address the requested change.
>
> On the other hand, the branch it's based on hasn't been updated since
> August last year, so I don't know if there are any plans to merge it into
> the master branch and release it any time soon.
>
> For what it's worth, this branch still works fine as-is if you build and
> install it yourself.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ckb-next/ckb-next/pull/809#issuecomment-1546794361>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A725RQEXCJXON2EXKHUE7CTXGBCSNANCNFSM5ST33NHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-05-14 03:40 UTC, minneyar commented
@tatokis Sorry for the (very) long delay on this; I cleaned up the above comments and brought this up to date with the target branch, and it looks like everything still works for me.  Let me know if there are any other issues.

@Hotshot0592 Building and installing it should be pretty straightforward; you'll want to clone my repo and checkout the `k70tkl` branch, then follow these instructions for building from source: https://github.com/ckb-next/ckb-next/wiki/Linux-Installation#build-from-source

2023-05-14 04:39 UTC, Hotshot0592 commented
Yeah, I copied it in python. Do I just throw it in terminal now?

On Sat, May 13, 2023, 10:40 PM minneyar ***@***.***> wrote:

> @tatokis <https://github.com/tatokis> Sorry for the (very) long delay on
> this; I cleaned up the above comments and brought this up to date with the
> target branch, and it looks like everything still works for me. Let me know
> if there are any other issues.
>
> @Hotshot0592 <https://github.com/Hotshot0592> Building and installing it
> should be pretty straightforward; you'll want to clone my repo and checkout
> the k70tkl branch, then follow these instructions for building from
> source:
> https://github.com/ckb-next/ckb-next/wiki/Linux-Installation#build-from-source
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ckb-next/ckb-next/pull/809#issuecomment-1546798905>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A725RQAEC636SCORH4SUESTXGBH3HANCNFSM5ST33NHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-14 04:50 UTC, minneyar commented
> Yeah, I copied it in python. Do I just throw it in terminal now?

There's no need to do anything in Python, the commands in the wiki are what you'd run in a terminal to clone and build the repository; although GitHub successfully built packages from my branch, so you can probably just download the artifacts here and install the right package for your platform: https://github.com/minneyar/ckb-next/actions/runs/4970360775

2023-05-14 05:04 UTC, Hotshot0592 commented
Now I have ckb-next installed already. Do I just update it somehow?

On Sat, May 13, 2023, 11:50 PM minneyar ***@***.***> wrote:

> Yeah, I copied it in python. Do I just throw it in terminal now?
>
> There's no need to do anything in Python, the commands in the wiki are
> what you'd run in a terminal to clone and build the repository; although
> GitHub successfully built packages from my branch, so you can probably just
> download the artifacts here and install the right package for your
> platform: https://github.com/minneyar/ckb-next/actions/runs/4970360775
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ckb-next/ckb-next/pull/809#issuecomment-1546806760>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A725RQHW6TWMKSTTXNG522LXGBQCRANCNFSM5ST33NHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-14 05:05 UTC, Hotshot0592 commented
Again, sorry. Completely new.

On Sat, May 13, 2023, 11:50 PM minneyar ***@***.***> wrote:

> Yeah, I copied it in python. Do I just throw it in terminal now?
>
> There's no need to do anything in Python, the commands in the wiki are
> what you'd run in a terminal to clone and build the repository; although
> GitHub successfully built packages from my branch, so you can probably just
> download the artifacts here and install the right package for your
> platform: https://github.com/minneyar/ckb-next/actions/runs/4970360775
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ckb-next/ckb-next/pull/809#issuecomment-1546806760>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A725RQHW6TWMKSTTXNG522LXGBQCRANCNFSM5ST33NHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-14 05:11 UTC, minneyar commented
> Now I have ckb-next installed already. Do I just update it somehow?

Normally installing a newer version of a package will automatically update it, but it might not in this case since the version number in my branch hasn't changed from the source branch.  It's probably easiest to uninstall the ckb-next package you had previous installed, then install the one built from my repo, although exact instructions on how to do that could vary depending on what Linux distro you're using.

2023-05-14 13:41 UTC, Hotshot0592 commented
So I keep getting an error when downloading your package.
![image_2023-05-14_084127787](https://github.com/ckb-next/ckb-next/assets/133552320/8c57227a-a58e-48dd-bde4-ab804c77d0d2)

2023-05-14 13:43 UTC, Hotshot0592 commented
I'm using Nobara, which is derived from Fedora if that helps at all. Also, I tried both of the Fedora packages you have on there.

2023-05-14 14:09 UTC, minneyar commented
I think Nobara is based on Fedora 37, which is newer than any of the packages that were being generated by that build.  I added Fedora 37 and rebuilt it, so try the `ckb-next.fedora-37.GNU.Release.rpm` package from this one: https://github.com/minneyar/ckb-next/actions/runs/4972785546

2023-05-14 14:14 UTC, Hotshot0592 commented
I tried and this is what I got.
![Screenshot from 2023-05-14 09-13-26](https://github.com/ckb-next/ckb-next/assets/133552320/7c6dcc8e-9852-4ae9-90a4-4d4723a2355e)

2023-05-14 17:30 UTC, minneyar commented
Hmm.  Unfortunately, I'm not really very familiar with Red Hat or its packaging system enough to debug why it doesn't like that; at this point it's probably easier to try building it from source.

For reference, the commands you'd run in a terminal to do that but using my fork and branch instead of this repo would look like:

1. Install prerequisites
   ```
   sudo dnf install gcc gcc-c++ make cmake glibc zlib-devel qt5-qtbase-devel quazip-qt5-devel systemd-devel pulseaudio-libs-devel qt5-linguist qt5-qtx11extras-devel xcb-util-wm-devel xcb-util-devel libxcb-devel git dbusmenu-qt5-devel
   ```
2. Clone the repo, cd into it, checkout the branch:
   ```
   git clone https://github.com/minneyar/ckb-next.git
   cd ckb-next
   git checkout k70tkl
   ```
3. Run the script to build and install it:
   ```
   ./quickinstall
   ```

2023-05-15 02:18 UTC, Hotshot0592 commented
I got it working, thanks! Now I have been doing all of this to see if one program will work. It is call STO Keybind, it is for Star Trek Online. It works just fine on windows (shocker right) and now when I go to select what key I want to do what with it pulls up on a blank drop down. Everything up to that point works. Any idea where I can go to post about this? I thought it needed drivers for it to work and detect my keyboard. But Idk if that is still the case or not.

2023-05-15 04:46 UTC, Hotshot0592 commented
Could part of the issue be that I am getting an error when I try updating my flatpak? But I cannot update the cbk-next due to some error saying that the directory does not exist.

2023-06-23 15:59 UTC, tatokis commented
@minneyar Apologies for the late reply. I ended up writing some code to simplify keymap patching (which means there's no need to manually delete patched keymap entries anymore).

I made some minor changes and rebased against master (which I merged the k100-v2 branch into earlier). Keep in mind I force pushed.

Please verify that everything still functions as expected, and if so, I'll merge it.

2023-06-23 20:07 UTC, HiWhatName commented
Can confirm, it's fully functional.

2023-06-23 23:16 UTC, minneyar commented
Yep, I just tried it out and it looks good to me.

2023-06-24 12:07 UTC, merged

2024-01-18 13:19 UTC, MysteriousRSA commented
Has there been any updates on this?

When i install ckb-next it doesnt show still and is listed as requested in the supported devices, same with... all of my other peripherals

2024-01-18 13:48 UTC, enigamus commented
> Has there been any updates on this?
> 
> When i install ckb-next it doesnt show still and is listed as requested in the supported devices, same with... all of my other peripherals

This was about K70 RGB TKL Mechanical, you may have the K70 RGB TKL Optical-Mechanical Keyboard (with Corsair Opx). 
If you run `ckb-next-dev-detect` and look for idProduct, "0x1b73" is supported, "0x1bb9" is not.

There is an [open  issue](https://github.com/ckb-next/ckb-next/issues/1003).

2024-01-23 20:12 UTC, discotimetraveler commented
I just found this software and this post. I have the K70 TKL Mechanical version and I installed from apt-get (0.6.0) and my keyboard is not detected...? (My mouse is detected in the software)....   my -dev-detect...

idProduct          0x1b73 CORSAIR K70 RGB TKL CHAMPION SERIES Mechanical Gaming Keyboard

$ ckb-next -v
ckb-next 0.6.0

I have the latest bios. I was using the same keyboard on WIn11 on the same system. It's an Intel NUC so not a lot of USB ports. I went through the basic TS steps; other ports, reboot, unplug/plug, I don't think this keyboard has a BIOS switch (just this tournament switch)....  Any suggestions?

Running Debian (Sparky 8) with 6.6.11 kernel.

Thanks!